### ISSUE TITLE
octokat.js

### ISSUE THREAD

**Issue by deanrad** [MeteorPackaging/discussions#23]
From https://github.com/chicagogrooves/deanius-meteor-octokat

**Comment by splendido** [comment]
so you would like to fork [this repo](https://github.com/philschatz/octokat.js)?

**Comment by deanrad** [comment]
Well I think so.. I'd like to add fiber-based methods to what is already published, so is fork-and-add the strategy ?

**Comment by splendido** [comment]
But you already have your `deanius:octokat` package right?
Would you like to turn it into an official porting for Meteor?
...am I missing something?

**Comment by deanrad** [comment]
Sorry @splendido I ran out of steam on this.. Let's start this on a different repo when I have more time to focus. Thanks for your help so far.
