### ISSUE TITLE
Fork of lunr.js - wrapped for Meteor

### ISSUE THREAD

**Issue by lb-** [MeteorPackaging/discussions#28]
Hi,

I am currently maintaining this fork of lunr.js
https://github.com/lb-/lunr.js

I submitted a pull request a while ago but reversed it, this wrapper package is available on Atmosphere here: https://atmospherejs.com/lbee/lunr

Might be worth putting on your main list https://github.com/MeteorPackaging or happy to take any suggestions about improvements to what I have changed in my fork.

thanks heaps.

**Comment by lb-** [comment]
Also, I have been reading more of the main discussion thread here: https://github.com/MeteorCommunity/discussions/issues/14

Should I also set up the lunr namespace on atmosphere?
both http://atmospherejs.com/lunr and http://atmospherejs.com/lunrjs are free currently

**Comment by splendido** [comment]
Yep, reserve them by creating a new organization!

Which repo would you like to see forked under MeteorPackaging?

**Comment by lb-** [comment]
@splendido I have created the organization: https://atmospherejs.com/lunr
I have added @dandv as a member of that organisation also.

The repo I would like to see forked is this one: https://atmospherejs.com/lbee/lunr

If I can then be given access to the repo I will edit it to be in the new organisation namespace & deprecate the old package under my namespace.

Hope I am following the process well :smile:

**Comment by splendido** [comment]
Hello @lb- !
...have you by chance followed [this discussion](https://github.com/MeteorPackaging/discussions/issues/18)?

If you agree on the process, I can create a new repo to start up the wrapping :-)

**Comment by lb-** [comment]
Do you mean the sister approach, that would make sense as the author has not responded to a previous PR about bringing the meteor files back into their repo https://github.com/olivernn/lunr.js/issues/128 .

Still learning but I understand I will have to manually copy over my meteor components as the git submodule will be created from the original repo: https://github.com/olivernn/lunr.js

**Comment by splendido** [comment]
yep!
...and provide some tests, in case you still don't have some.

Would you like me to create the new repo?
would `lunr-wrapper` be fine?
...also, are there any other _plugin_ packages around for lunr?

**Comment by lb-** [comment]
yep of course - I have some tests and will migrate them over + do the other set up (maybe not tonight but when I get to it)

The only other package of this on Atmosphere is an old mrt one: `momentjs:moment`
Cannot find any other plugins for lunr.js only blogs/posts about integrating with different sites.

**Comment by lb-** [comment]
`lunr-wrapper` is also fine, makes sense

**Comment by splendido** [comment]
Ok, see [lunr-wrapper](https://github.com/MeteorPackaging/lunr-wrapper) (just the repo name, btw...)
I've just added you to the [lunrjs](https://github.com/orgs/MeteorPackaging/teams/lunrjs) team.

You can start by copying stuff from the other wrappers linked above.

Please add also `meteorpublish` and me to the `lunr` organization :)

**Comment by lb-** [comment]
Great thanks!

You and `meteorpublish` have been added to the organisation. will get on it
