### ISSUE TITLE
sweetalert

### ISSUE THREAD

**Issue by ecwyne** [MeteorPackaging/discussions#29]
@dandv 

I would like to fork https://github.com/t4t5/sweetalert into the MeteorPackaging organization to make an official Meteor package.

Just starting with step 1 of the [autopublish wiki](https://github.com/MeteorPackaging/autopublish.meteor.com/wiki#step-by-step-guide)

**Comment by dandv** [comment]
Hey Eric,

There are already a few sweetAlert wrappers - https://atmospherejs.com/?q=sweet

Have you looked into them?

**Comment by ecwyne** [comment]
I have looked into them, and have actually [contributed](https://github.com/kevohagan/meteor-sweetalert/commits?author=ecwyne) to help keep them up to date. I'm interested in using autopublish to tie in directly to the original author's repo.

**Comment by splendido** [comment]
@dandv, @ecwyne, lets go with the new approach!
...I'm loving it! :-)

I've set up the [wrapper for ramda](https://github.com/MeteorPackaging/ramda-wrapper) in less than half an hour yesterday, and there's almost no need to get in touch with the original authors.
...even though, gettin a webhook from them would be great!
