### ISSUE TITLE
Current problems?

### ISSUE THREAD

**Issue by benjick** [MeteorPackaging/discussions#32]
Drafted a release just now (https://github.com/benjick/meteor-stripe-native/releases/tag/1.1.1) but autopublish didn't pick it up. Just checking in if there is any current problems. 

Cheers
Max

**Comment by benjick** [comment]
Omg, it was just so fast... Sorry, I'm blind

**Comment by benjick** [comment]
Okay, so it never got published on Atmosphere, but autopublish reports it at version 1.1.1. Atmosphere says 1.1.0

**Comment by splendido** [comment]
hello @benjick!

I'm sorry we're in the middle of a quite big refactor of the code to improve security.
Subscriptions and hook have now to be manually approved by admins before getting them working...
...and this part is still to be documented.
I also have plan to report triggers for unapproved subscriptions with automatic issue creation, but this will be for the next month I  guess.

Btw, I've just approved both your packages!
It should be fine now, let me know!

Thanks for trying out autopublish.meteor.com :-)

**Comment by splendido** [comment]
P.S. autopublish.meteor.com picks up the version form the `package.js` file....

**Comment by benjick** [comment]
Thank you @splendido!

Is there a way to push my latest version or should I create a new release?

**Comment by splendido** [comment]
You can re-deliver the last webhook payload.
Lets have a look under your repo's settings-> webhooks.
If you open the details about the webhook pointing to autopublish you should see the list of last deliveries and choose to send them again

**Comment by benjick** [comment]
Cheers, that worked! Thank you!
