### ISSUE TITLE
Can I package canvg?

### ISSUE THREAD

**Issue by chmac** [MeteorPackaging/discussions#37]
I was about to whip up a personal package and push it to atmosphere, but it'd be much cooler if we could get one going on here.

This is what I want to package:
https://github.com/gabelerner/canvg

It's pretty simple, just requires the include of a couple of js files. I'm optimistic that the author will accept a PR to add a `package.js` file to their repo. :-)

**Comment by splendido** [comment]
At the moment we're having some problem with autopublish.meteor.com, but we can continue to create official wrappers as long as we're keen to keep them up to date by hands...

the wrapper could look something like [jspdf-core-wrapper](https://github.com/MeteorPackaging/jspdf-core-wrapper).
Would you like me to create a repository for you to wrap to original repo?

or would you prefer to go for the PR on the official repo (so you need a fork here)?

**Comment by chmac** [comment]
Probably best to forget about it for now. I'm not actively using the package on an ongoing basis, I was happy to do a little setup in order to get the package into atmosphere, but I'd prefer not to create yet another abandoned package...

**Comment by splendido** [comment]
If you wish...

feel free to prepare a repository following the _latest_ trend as explained [here](https://github.com/MeteorPackaging/autopublish.meteor.com/wiki/Wrapping-3rd-Party-Packages) (WIP), it should take about an hour not more.

Make sure you get an organization namespace reserved for the new official package and add @dandv, @splendido, @zimme, and whoever else you think should be in among its members.

Once you think you're good to go (which means tests pass...) feel free to publish the package and transfer ownership of your repository to [MeteorPackaging](https://github.com/MeteorPackaging). We'll then organize teams and permissions.
...or write a comment here when you think you're ready to get a final review before actual publish.
