### ISSUE TITLE
d3

### ISSUE THREAD

**Issue by dandv** [MeteorPackaging/discussions#4]
[@splendido's PR to d3 was merged](https://github.com/mbostock/d3/pull/2130#issuecomment-73420656) on 2015-02-08. [W00t](https://twitter.com/dandv/status/564696500328886273).

CC @zimme, @splendido  - I've added `meteorpublish` to the MD org. Will be deleting the messages from the [OT](https://github.com/MeteorCommunity/discussions/issues/14) to reduce clutter.

**Comment by splendido** [comment]
I've just removed any record about d3 from autopublish.
Mike will continue to publish it by hands.

One successful integration, in any case!
Tnx @dandv!

**Comment by garrilla** [comment]
Sorry to raise this from the dead guys.

Please see my comment re version status at https://github.com/mbostock/d3/pull/2130#issuecomment-155593042

**Comment by splendido** [comment]
I really don't know what to do with this, since mboostock explicitely asked to make new publishes on his own...
What do you guys think?
