### ISSUE TITLE
Packaging simplemde-markdown-editor

### ISSUE THREAD

**Issue by rshipp** [MeteorPackaging/discussions#49]
I'd like to create a Meteor package for the third-party library https://github.com/NextStepWebs/simplemde-markdown-editor.

Assuming [this](http://www.meteorpedia.com/read/Packaging_existing_Libraries) is still accurate, could I get access to fork the library to the MeteorPackaging org?

Thanks

**Comment by splendido** [comment]
Hello @rshipp!
Could you please have a look at [this comment](https://github.com/MeteorCommunity/discussions/issues/14#issuecomment-140304061)?
I'm not pretending you had to read it before posting here, it's just to save a bit of time ;-)

**Comment by rshipp** [comment]
Ok, thanks, I'll take a look at the jspdf repos. Should I still register a group name like "nextwebsteps" on atmosphere for the namespace? I'm not sure how this works - I don't want it to look like I'm trying to represent nextwebsteps, since I'm not affiliated with them, but that seems to be the current recommended practice.

**Comment by zimme** [comment]
@rshipp I've registered `nextwebsteps` organization on meteor.com/atmospherejs.com because I was actually going to package simplemde but I never got to it.

Ping me when your done with it and I'll give you access to the namespace.

**Comment by zimme** [comment]
I don't see a problem with us trying to package up things under their proper names and organizations as long as we're willing to change it or release control over it to the people behind the real project.

**Comment by rshipp** [comment]
There's a start [here](https://github.com/rshipp/simplemde-wrapper), but I'm not sure how to test it without uploading to Atmosphere. Specifically, I'm worried about whether the addFiles/addAssets calls are correct, since I seem to remember there being some hardcoded path issues with the CSS for lepture's original Editor.

**Comment by splendido** [comment]
Could [this](https://github.com/Semantic-Org/Semantic-UI/blob/master/test/meteor/assets.js) be useful?
