### ISSUE TITLE
Access for new library integration

### ISSUE THREAD

**Issue by Data-Meister** [MeteorPackaging/discussions#51]
Hi there, I'm looking to integrate a third party library into meteor.  please could you grant me access?

I landed from here: http://www.meteorpedia.com/read/Packaging_existing_Libraries

**Comment by splendido** [comment]
@Data-Meister which library are you going to package?

Please feel free to prepare a repository following the _latest_ trend as explained [here](https://github.com/MeteorPackaging/autopublish.meteor.com/wiki/Wrapping-3rd-Party-Packages) (WIP)

Make sure you get an organization namespace reserved for the new official package and add @dandv, @splendido, @zimme, and whoever else you think should be in among its members.

Once you think you're good to go (which means tests pass...) feel free transfer the ownership of your repository to [MeteorPackaging](https://github.com/MeteorPackaging). We'll then organize teams and permissions and eventually publish the package.

...or write a comment here when you think you're ready to get a final review before actual publish.

**Comment by Data-Meister** [comment]
Great, thanks for explaining the process!
