### ISSUE TITLE
Add package from github? (not available on atmosphere)

### ISSUE THREAD

**Issue by roytz** [MeteorPackaging/discussions#53]
Hi,
I'm trying to add the md-data-table (https://github.com/daniel-nagy/md-data-table) package to my meteor project.
I've git cloned the fork into my packages folder but when I executed the "meteor add angular-material-data-table" command I got a message saying there's no such package. What am I doing wrong? How do I make it a meteor package?
Thanks!

**Comment by dandv** [comment]
Meteor 1.3 brings npm module integration. The 3rd party package wrapping system that we've worked so hard on will be finally obsolete.
