### ISSUE TITLE
Lo-Dash

### ISSUE THREAD

**Issue by erasaur** [MeteorPackaging/discussions#9]
See [here](https://github.com/erasaur/meteor-lodash/issues/2) for context. I'm willing to setup an official package but am still waiting for comment on what is the best way to proceed with this (as a disclaimer, I don't have much experience with packaging for Meteor).

**Comment by bobiblazeski** [comment]
Mdg seems ready to switch from underscore to lodash so might be better to wait https://github.com/meteor/meteor/issues/1009 since there's already up to date wrapper https://atmospherejs.com/erasaur/meteor-lodash

**Comment by splendido** [comment]
Hello @erasaur,
lets try to follow the [step by step guide](https://github.com/MeteorPackaging/autopublish.meteor.com/wiki#step-by-step-guide) on the [wiki](https://github.com/MeteorPackaging/autopublish.meteor.com/wiki)

Actually there's already [a forked repo](https://github.com/MeteorPackaging/lodash) for it.
In case you're willing to try, I'll give you write access to it! Just let me know...

Cheers,
Luca

**Comment by erasaur** [comment]
Hey @splendido, thanks for the reply. What exactly is missing from the existing forked repo (i.e has any setup been done)? It looks like lodash doesn't use a build system, so I'm assuming I just need to add a `package.js` file?

**Comment by erasaur** [comment]
On another thought, since Meteor will be eventually adopting lodash anyway, it will be sufficient (and simpler) to just maintain a non-official package in the meantime. Thanks for your help.

**Comment by splendido** [comment]
Ok, lets see what happens...
Cheers,
Luca
